module.exports = {
  SALT_ROUNDS: parseInt(process.env.SALT_ROUNDS),
  SECRET: process.env.SECRET,
  GOOGLE_API_KEY: process.env.GOOGLE_API_KEY,
  GRASSHOPPER_API_KEY: process.env.GRASSHOPPER_API_KEY,
  MONGODB_URI: process.env.MONGODB_URI,
  CLOUDINARY_NAME: process.env.CLOUDINARY_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET
};